### ISSUE TITLE
issues with dot files on Android

### ISSUE THREAD

**Issue by epegzz** [markmarijnissen/cordova-app-loader#28]
I have a ".nomedia" file in my `cordova/www` directory (and in my manifest.json).
But while all other files are getting copied to the persistent storage just fine after running an update, the ".nomedia" file won't be there.

Beside having issues copying a file starting with a dot, using hidden directories as `localRoot` also causes issues.

I tried to use `myApp/.app` or `myApp/.app/` as `localRoot` var which both breaks the updating process in different ways:

When using `myApp/.app` the downloaded filenames will be concatinated in a way that an `index.html` becomes an `.appindex.html` within the `myApp` folder.

When using `myApp/.app/` the files are getting copied just fine, but the next update check will just hang and stop to work at all.

When using `myApp/app` everything works fine.

The reason why I want to use a dotfile directory or add a `.nomedia` file is so that the app assets are not getting indexed by the android gallery app.

Any idea why dot files seem to be an issue?

**Comment by markmarijnissen** [comment]
Everything starting with a dot is ignored by the cache, so the cache mistakingly believes the update has failed because it cannot find any files.

This was fixed in the recent release in March (0.15 or 0.16). Have you checked that?

Also, the Manifest should be all-inclusive, meaning, all files that are NOT in the Manifest will be deleted. Design rationale is that you're allowed to change your file structure, and you don't want (potentially big) files to linger around. Best solution would be to include the .media file in your manifest, or to set the .media file in the parent directory of the appcache (i.e. in `/myApp/.nomedia` and then cache in `/myApp/app`).

Is there any particular reason, btw, you want to folder to start with a `.`?

**Comment by epegzz** [comment]
I tried v0.17 but it still does not write the `.nomedia` file into cache. 
I am getting this `FileTransferError`:
```json
body: null
code: 1
exception: "www/.nomedia"
http_status: null
source: "file:///android_asset/www/.nomedia"
target: "cdvfile://localhost/persistent/novobeat/.nomedia"
```

And yeah, the `.nomedia` file IS in the manifest.

To answer your other question: The `.nomedia` file should be put there in order to prevent app assets from showing up in the android gallery app. Another way of achieving it this is to put the assets into a 'hidden' folder (more info [here](http://www.addictivetips.com/mobile/how-to-prevent-a-directory-from-being-scanned-by-android-gallery/)). That's what I was trying after the `.nomedia` file was not copied.

**Comment by epegzz** [comment]
Seems the issues with `.nomedia` file is not related to the app loader. Turned out that the webserver serving the updated files appearently does not serve hidden files.

**Comment by epegzz** [comment]
Update: After making sure the `.nomedia` file is being served from the webserver, i still get the same `FileTransferError` :(

**Comment by epegzz** [comment]
Update: The issue was gone once i put some content in the file. If the `.nomedia` file is not empty, then no `FileTransferError` occurs. For me this is sufficient :)

**Comment by markmarijnissen** [comment]
Interesting to know. Good there is a work-a-round. 

I'll update the FAQ in the Readme and close the issue.

**Comment by ObjectiveTruth** [comment]
Closing issue since it appears to have been resolved. If there's any other input please reopen the issue :ok_hand:
